    baseURL = 'https://migcay.github.io/practica_hugo/'
languageCode = 'en-us'
title = 'MI PRACTICA HUGO'

theme= "zen"
sectionPagesMenu = "main"
[params]
  mainSections = ["sobre mi", "Markdown", "Markdown"]

  [markup]
    [markup.goldmark]
      [markup.goldmark.renderer]
        unsafe = true
